export default items = [
"Set Foot on North America, South America, Asia, Europe, Australia, Antarctica and Africa",
"Ride in a Hot Air Balloon",
"Personally Know Someone Famous",
"Dance with Miss America",
"Swim with a Dolphin",
"Learn a Foreign Language and Actually Use It",
"Have my Portrait Painted",
"Watch a Space Shuttle Launch",
"Be an Extra in a Film",
"Skydive",
"Scuba Dive",
"Ride a Train",
"Be a Member of a Studio Audience",
"Send a Message in a Bottle and get a Response",
"Go to Space",
"Plant a Tree and Watch it Grow",
"Learn to Ballroom Dance -Properly",
"Sit on a Jury",
"Write an Autobiography",
"Be Someone&#8217;s Mentor",
"Shower in a Waterfall",
"Learn to Legitimately Play a Song on any Musical Instrument",
"Teach someone illiterate to read",
"Spend the night in a haunted place",
"See a Lunar Eclipse",
"Spend New Year&#8217;s Eve in Times Square",
"Drive Across America Coast-to-Coast",
"Go Snow Skiing",
"Crash an extravagant wedding",
"Write my will",
"Sleep under the stars",
"Go white-water rafting",
"Own my own house",
"Grow a garden and eat the produce",
"Have six-pack abs",
"Go Deep Sea Fishing",
"Spend time at a concentration camp",
"Create a Family Tree",
"Spoil my grandchildren",
"Catch a foul ball or home-run at a MLB game",
"Hit a hole-in-one",
"Run a marathon",
"Swim with sharks",
"Experience weightlessness &#8211; no gravity",
"Go to a sumo wrestling match",
"See a tornado touch ground",
"Go to an active volcano",
"Go to a nudist colony",
"Travel on a safari",
"Ride a bull",
"Run with the bulls in Pamplona",
"Attend a Jewish wedding",
"Go to a Pow-Wow",
"Ride a cable car in San Francisco",
"Watch the Yankees-Red Sox in Fenway Park and Yankee Stadium",
"Try to make a guard laugh at Buckingham Palace",
"Walk a length of the Great Wall of China",
"Go to a drive-in movie theater",
"See MtRushmore",
"Drive an 18-wheeler",
"Eat a meal from a world-class chef",
"Crash a Hollywood Studio",
"Meet someone famous randomly",
"Spend a day in a spa",
"Walk the red carpet at a huge event",
"Stay at a 5-star hotel",
"See Stonehenge",
"Stand next to a pyramid",
"Ride a Gondola in Venice",
"Take a yoga class",
"Take a photography class",
"Shake hands with a President",
"Learn how to sail",
"See the Northern Lights",
"Kiss on top the Eiffel Tower",
"Learn to Juggle",
"Get a tattoo",
"Crowd Surf at a rock concert",
"Bungy Jump",
"Save someone&#8217;s life",
"Get a book published",
"Get a standing ovation",
"Kill a wild game animal",
"Make a clay pot",
"Relax in Tahiti for at least two weeks",
"Live abroad",
"Eat frog legs and gumbo and shrimp in the Deep South",
"Snowboard",
"Be on a game show",
"Go treasure hunting",
"Be involved in a heist",
"Own a pet monkey",
"Land a flip on a wakeboard",
"Surf the waves in Hawaii",
"Enter a professional Ping-Pong tournament",
"Give my daughter away at her wedding to a man who deserves her",
"Watch the sunset on a beach on my honeymoon",
"Coach my son&#8217;s little league baseball team",
"Run my own successful business",
"0Watch OU-Texas at the Red River Rivalry",
"Walk across hot coals",
"Go to all 50 U.SStates",
"Be on a Reality TV show.",
"Be completely out of debt.",
"Go on a cruise.",
"Drive through a Redwood Tree.",
"Ride the Skycoaster at the Royal Gorge",
"Go to the Summer Olympic Games",
"Have acupuncture",
"Visit the Hoover Dam",
"Climb Chichen Itza",
"Stand beside the Christ the Redeemer statue",
"Walk around the Colosseum in Rome",
"Visit Machu Picchu",
"Explore Petra",
"Take a picture in front of the Taj Mahal",
"Adopt a child",
"Travel to the center of all religion, Jerusalem",
"Ride a Segway",
"Attend a World Cup Match",
"Go Ice Fishing",
"Take the Polar Plunge in a cold weather country",
"Give a commencement speech",
"Sleep on a Trampoline",
"Swim in every ocean",
"Fly an airplane",
"Go to a NASCAR race",
"Have a street named after me",
"Tour the White House",
"Set a World Record",
"Get something patented",
"Catch a trout while fly fishing",
"Eat at a Brazilian Steakhouse in Brazil",
"Visit an orphanage in a foreign country",
"Ride a Double Decker Bus in London",
"Set atop the London Eye",
"Get my Ph.D",
"Complete the Hawaii IRONMAN Challenge",
"Draw a charge from Nick Collison in a pickup basketball game",
"Give a speech to over 10,000 people",
"Attend the Iditarod",
"Baptize somebody somewhere cool",
"Be an Olympian",
"Be in a community theater",
"Be in the $40,000 plus speaking club",
"Be interviewed on national morning show",
"Be invited onto a professional court/field",
"Be invited to the white house",
"Be the world champion of public speaking",
"Build a treehouse",
"Buy someone a house",
"Camp in a national park",
"Carry the olympic torch",
"Climb a lighthouse",
"Complete a 40 day fast",
"Crank my neck upward at the Sistine Chapel",
"Create a board game",
"Dance with an African Tribe",
"Dig a well for community",
"Eat at Michelin award-winning restaurant",
"Eat chocolate in Switzerland",
"Encircle a giant sequoia at Yosemite National Park",
"Finish a corn maze",
"Fly a kite with my girls on the beach",
"Fly in a private jet",
"Get gas at the world&#8217;s largest truck stop",
"Give a $10,000 gift to charity",
"Give a $25,000 gift",
"Give a $50,000 gift",
"Give away a car",
"Go indoor skydiving",
"Go on a 30 Day leadership adventure",
"Go whale watching",
"Go Zorbing",
"Golf at Pebble Beach",
"Graduate with a master&#8217;s degree",
"Have a book published",
"Have a conversation in 2 second languages",
"Hear Niagara Falls",
"Help build an orphanage",
"Hike in the Grand Canyon",
"Hike part of the Appalachians",
"Host a Christmas party for people with nowhere to go",
"Host a collection (10 piece min)",
"Host a foreign exchange student",
"Host a leadership training in Antarctica",
"Invent a well-known game",
"Kiss the Blarney Stone",
"Live in NYC for 6 months",
"Make a scrapbook with each child",
"Marvel at Aurora Borealis",
"Meet the POTUS",
"Mush a dog sled",
"Own a house outright",
"Own a cool antique",
"Own a pinball machine",
"Own a signed copy of &#8220;Giving Tree&#8221;",
"Parasail",
"Participate in a reenactment",
"Plant a master&#8217;s commission or ministry school",
"Play bocce ball",
"Pray in the holy land",
"Preach in a foreign country",
"Push a stone at Stonehenge",
"Quote scripture at Christ the Redeemer",
"Raise $1 million in 1 fundraiser",
"Raise my arms on the top 5 coasters in the world",
"Read 52 book in 1 year",
"Read the Bible in 7 different translations",
"Read the complete works of C.SLewis",
"Read the top 100 books of all time",
"Read the works of John Maxwell",
"Receive an honorary degree",
"Ride a camel in its natural environment",
"Ride a roller coaster at Cedarpoint",
"Ride an ostrich",
"Ride in a gondola",
"Ride in a helicopter",
"Run a 1/2 marathon",
"RV across part of America",
"Say something profound which becomes a famous quote",
"See a bear catch a salmon",
"See Adele in concert",
"See blinded eyes open",
"See Old Faithful erupt in Yellowstone",
"See the Acropolis in Greece",
"Shake hands with a matador",
"Share my faith in a communist nation",
"Share my faith in an Islamic nation",
"Sing in Silver Dollar City",
"Sleep in a castle",
"Sleep in a rainforest",
"Eat in a food challenge",
"Speak to a group with the assistance of a translator",
"Stand on the equator",
"Start a family christmas tradition",
"Start a phenomenon",
"Start a scholarship fund/program",
"Swim at Schlitterbahn",
"Swim in a great lake",
"Swim in the dead sea",
"Swim the Great Barrier Reef",
"Tackle a Food Challenge",
"Take a Bus ride to Chichen Itza",
"Take a cooking class",
"Take a ferry to the Statue of Liberty",
"Take a road trip",
"Take a spiritual retreat in a cabin",
"Take an art class",
"Take my family to all 4 Disney World parks",
"Throw a birthday party for someone who can&#8217;t have one",
"Throw out a first pitch",
"Touch an Easter Island Moíai",
"Tour the Great Pyramids",
"Travel with Nomads",
"Visit 50 (or better) national parks",
"Visit 50 countries by 50 years of age",
"Visit Angkor Wat",
"Visit Anne Frank&#8217;s house",
"Visit Boston",
"Visit Elephant National Park in Thailand",
"Visit Neuschweinstein Castle in Germany",
"Visit Petra, Jordan",
"Visit the 5 longest rivers in the world",
"Visit the Galapagos Islands",
"Visit the world&#8217;s 5 greatest museums",
"Jump off of a bridge",
"Walk the Camino Del Rey",
"Wash an elephant",
"Watch a world cup match in Brazil",
"Watch migration on the Serengeti",
"Watch the final four in person",
"Watch the whiling dervishes in Istanbul",
"Water ski",
"Write a book",
"Write a children&#8217;s book",
"Land a backflip",
"Yell &#8220;are you not entertained&#8221; at the Colosseum",
"Win a Gold Medal at the Olympics",
"Take a punch from Mike Tyson",
"Get married to the love of my life"];